In [62]:
import numpy as np

list Vs Numpy - Time Taken

In [63]:
from time import process_time

Time taken for task in List 

In [64]:
python_list = [i for i in range(1000000)]

start_time =process_time()

python_list = [i+5 for i in python_list]

end_time = process_time()

print(end_time - start_time)

0.078125


In [65]:
np_array = np.array([i for i in range(1000000)])

start_time = process_time()

np_array+=5

end_time = process_time()

print(end_time - start_time)

0.0


Numpy Arrays

In [66]:
#initiating  a list

list1 = [1,2,3,4,5]
print(list1)
type(list1)

[1, 2, 3, 4, 5]


list

In [67]:
#initializing numpy array
np_array = np.array([1,2,3,4,5])
print(np_array)
type(np_array)

[1 2 3 4 5]


numpy.ndarray

In [68]:
#creating a 1D array
a= np.array([1,2,3,4])
a.shape


(4,)

In [69]:
#creating 2D Array
b = np.array([(1,2,3),(4,5,6)])
b.shape

(2, 3)

In [70]:
#creating array with floating values

c = np.array([(1,2,3,4),(5,6,7,8)], dtype=float)
print(c)

[[1. 2. 3. 4.]
 [5. 6. 7. 8.]]


In [71]:
#setting initial placeholders in numpy arrays

v=np.zeros((4,5)) # creates a 4x5 matrix with all values as Zeros
print(v)
b = np.ones((3,3)) # creates a 3x3 matrix array with all vlues as ones
print(b)
u = np.full((5,4),5) # creates a 5x4 array with all vlues as 5
print(u)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
[[5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]]


In [72]:
# creating an identity matrics

j = np.eye(8) #creates an identity matric with 8x8 shape
print(j)

[[1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 1.]]


In [73]:
#creating np array with random values

o = np.random.random((3,4)) # creates a 3x4 array with 0 < random vlaues < 1
print(o)

#random intervalues within specific range

g = np.random.randint(10,100, (3,5)) # creates a 3x5 matric within range 10 and 100
print(g)

#array of evenly spaced values
n = np.linspace(10,30,5) # creates a 1d array with values between 10 and 30 with diffrence of 5 between the numbers
print (n)

[[0.83260142 0.74850802 0.64489554 0.30054713]
 [0.57936037 0.46267116 0.53835912 0.7445399 ]
 [0.7844835  0.19764843 0.68938155 0.78450733]]
[[81 54 14 82 62]
 [24 13 69 85 36]
 [98 61 83 78 90]]
[10. 15. 20. 25. 30.]


Analysing a Numpy Array

In [74]:
c = np.random.randint(10,90, (5,5))
print (c)

#array Dimention
print("Array shape")
print (c.shape)

#number of dimensions
print("number of Dimention")
print(c.ndim)

#number of elements in array
print("number of elements in array")
print(c.size)

#datatype of valyes in array
print("data types of values in array")

print(c.dtype)

[[80 33 50 45 63]
 [24 44 58 23 78]
 [12 82 76 59 35]
 [37 56 85 37 60]
 [57 89 81 53 41]]
Array shape
(5, 5)
number of Dimention
2
number of elements in array
25
data types of values in array
int32


Mathematical Operations on an np array

In [75]:
# for relular list, the "+" concantinates the list 
list1 = [1,2,3,4,5,6]
list2 = [3,4,5,6,7,8]

print(list1+list2) # concatenetes



[1, 2, 3, 4, 5, 6, 3, 4, 5, 6, 7, 8]


In [76]:
# for nimpy arrays

a = np.random.randint(0,10,(3,3))
b = np.random.randint(30,40,(3,3))

print ("addition")
print(a+b)
print("subtraction")
print(a-b)
print("Multiply")
print(a*b)
print("divide")
print(a/b)

addition
[[39 35 32]
 [33 37 42]
 [34 45 34]]
subtraction
[[-23 -35 -28]
 [-27 -37 -32]
 [-28 -33 -30]]
Multiply
[[248   0  60]
 [ 90   0 185]
 [ 93 234  64]]
divide
[[0.25806452 0.         0.06666667]
 [0.1        0.         0.13513514]
 [0.09677419 0.15384615 0.0625    ]]


In [77]:
#using math fuctions

print(np.add(a,b))
print(np.subtract(a,b))
print(np.multiply(a,b))
print(np.divide(a,b))

[[39 35 32]
 [33 37 42]
 [34 45 34]]
[[-23 -35 -28]
 [-27 -37 -32]
 [-28 -33 -30]]
[[248   0  60]
 [ 90   0 185]
 [ 93 234  64]]
[[0.25806452 0.         0.06666667]
 [0.1        0.         0.13513514]
 [0.09677419 0.15384615 0.0625    ]]


Array Manipulation

In [78]:
array = np.random.randint(0,10,(2,3))
print(array)
print("shape: ", array.shape)

#transpose
print("transpose")
trans_array = np.transpose(array)
print(trans_array)
print("shape: ", trans_array.shape)

#altternate transpose
print("\nalternate transpose way")
trans2_array = array.T
print(trans2_array)
print("shape: ", trans2_array)

[[1 8 2]
 [9 4 0]]
shape:  (2, 3)
transpose
[[1 9]
 [8 4]
 [2 0]]
shape:  (3, 2)

alternate transpose way
[[1 9]
 [8 4]
 [2 0]]
shape:  [[1 9]
 [8 4]
 [2 0]]


In [79]:
#reshaping array 
a= np.random.randint(0,10,(2,3))
print("old shape: ", a)

print("New SHape: ")
reshaped = a.reshape(3,2)
print(reshaped)

print("shape: ",reshaped.shape)

old shape:  [[0 6 5]
 [3 1 4]]
New SHape: 
[[0 6]
 [5 3]
 [1 4]]
shape:  (3, 2)
